# Try to find SphinxBase
# SPHINXBASE_FOUND
# SPHINXBASE_INCLUDE_DIRS
# SPHINXBASE_LIBRARIES
# SPHINXBASE_DEFINITIONS

find_package(PkgConfig QUIET)

pkg_check_modules(PC_SPHINXBASE sphinxbase)

find_path(SPHINXBASE_INCLUDE_DIRS cmd_ln.h
    HINTS ${PC_SPHINXBASE_INCLUDEDIR} ${PC_SPHINXBASE_INCLUDE_DIRS})
find_library(SPHINXBASE_LIBRARIES sphinxbase
    HINTS ${PC_SPHINXBASE_LIBRARY_DIRS} ${PC_SPHINXBASE_LIBDIR})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(SphinxBase DEFAULT_MSG
    SPHINXBASE_LIBRARIES SPHINXBASE_INCLUDE_DIRS)

list(APPEND SPHINXBASE_INCLUDE_DIRS ${PC_SPHINXBASE_INCLUDE_DIRS})

set(SPHINXBASE_VERSION ${PC_SPHINXBASE_VERSION})

mark_as_advanced(SPHINXBASE_INCLUDE_DIRS SPHINXBASE_LIBRARIES)