# Trys to find PythonQt
#
# PYTHONQT_LIBRARIES
# PYTHONQT_INCLUDE_DIRS

find_package(PythonLibs 2.7 REQUIRED)
find_path(PYTHONQT_INCLUDE_DIRS "PythonQt.h"
          HINTS "${CMAKE_INSTALL_PREFIX}/include/PythonQt")

find_library(PYTHONQT_LIBRARIES "PythonQt")

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(PythonQt DEFAULT_MSG
    PYTHONQT_LIBRARIES PYTHONQT_INCLUDE_DIRS
    PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS)

list(APPEND PYTHONQT_INCLUDE_DIRS ${PYTHON_INCLUDE_DIRS})
list(APPEND PYTHONQT_LIBRARIES ${PYTHON_LIBRARIES})

mark_as_advanced(PYTHONQT_INCLUDE_DIRS PYTHONQT_LIBRARIES)