# Try to find SphinxBase
# SPHINXBASE_FOUND
# SPHINXBASE_INCLUDE_DIRS
# SPHINXBASE_LIBRARIES
# SPHINXBASE_DEFINITIONS

find_package(PkgConfig)
pkg_check_modules(PC_SPHINXBASE QUIET sphinxbase)
set(SPHINXBASE_DEFINITIONS ${PC_SPHINXBASE_CFLAGS_OTHER})

find_path(SPHINXBASE_INCLUDE_DIR cmd_ln.h
    HINTS ${PC_SPHINXBASE_INCLUDEDIR} ${PC_SPHINXBASE_INCLUDE_DIRS})

find_library(SPHINXBASE_LIBRARY NAMES sphinxbase
    HINTS ${PC_SPHINXBASE_LIBDIR} ${PC_SPHINXBASE_LIBRARY_DIRS})

set(SPHINXBASE_INCLUDE_DIRS ${SPHINXBASE_INCLUDE_DIR})
set(SPHINXBASE_LIBRARIES ${SPHINXBASE_LIBRARY})

include(FindPackageHandleStandardArgs)
# handle the QUIETLY and REQUIRED arguments and set LIBXML2_FOUND to TRUE
# if all listed variables are TRUE
find_package_handle_standard_args(SphinxBase DEFAULT_MSG
    SPHINXBASE_LIBRARY SPHINXBASE_INCLUDE_DIR)

mark_as_advanced(SPHINXBASE_INCLUDE_DIR SPHINXBASE_LIBRARY)

