# Set up xdo
# XDO_INCLUDE_DIR
# XOD_LIBRARIES

find_path(XDO_INCLUDE_DIR "xdo.h")

if(XDO_INCLUDE_DIR STREQUAL "XDO_INCLUDE_DIR-NOTFOUND")
    set(XDO_INCLUDE_DIR "")
else(XDO_INCLUDE_DIR STREQUAL "XDO_INCLUDE_DIR-NOTFOUND")
    find_library(XDO_LIBRARIES "xdo")
    if(XDO_LIBRARIES STREQUAL "XDO_LIBRARIES-NOTFOUND")
        set(XDO_LIBRARIES "")
    endif(XDO_LIBRARIES STREQUAL "XDO_LIBRARIES-NOTFOUND")
    set(XDO_FOUND true)
endif(XDO_INCLUDE_DIR STREQUAL "XDO_INCLUDE_DIR-NOTFOUND")

find_package_handle_standard_args(XDO DEFAULT_MSG
    XDO_LIBRARIES XDO_INCLUDE_DIR)