# Set up xdo

find_path(XDO_INCLUDES "xdo.h")

if(XDO_INCLUDES STREQUAL "XDO_INCLUDES-NOTFOUND")
  set(XDO_INCLUDES "")
else(XDO_INCLUDES STREQUAL "XDO_INCLUDES-NOTFOUND")

find_library(XDO_LIBRARIES "xdo")
  if(XDO_LIBRARIES STREQUAL "XDO_LIBRARIES-NOTFOUND")
    set(XDO_LIBRARIES "")
    message(WARNING "XDO not found.")
  else(XDO_LIBRARIES STREQUAL "XDO_LIBRARIES-NOTFOUND")
    message(STATUS "Found XDO: ${XDO_LIBRARIES}")
  endif(XDO_LIBRARIES STREQUAL "XDO_LIBRARIES-NOTFOUND")
  set(XDO_FOUND true)
endif(XDO_INCLUDES STREQUAL "XDO_INCLUDES-NOTFOUND")

