# Try to find PocketSphinx
# POCKETSPHINX_FOUND
# POCKETSPHINX_INCLUDE_DIRS
# POCKETSPHINX_LIBRARIES
# POCKETSPHINX_DEFINITIONS
# POCKETSPHINX_MODELDIR

find_package(PkgConfig QUIET)
pkg_check_modules(PC_POCKETSPHINX pocketsphinx)

find_path(POCKETSPHINX_INCLUDE_DIRS pocketsphinx.h
    HINTS ${PC_POCKETSPHINX_INCLUDEDIR} ${PC_POCKETSPHINX_INCLUDE_DIRS}
    PATH_SUFFIXES pocketsphinx)
find_library(POCKETSPHINX_LIBRARIES pocketsphinx
    HINTS ${PC_POCKETSPHINX_LIBRARY_DIRS} ${PC_POCKETSPHINX_LIBDIR})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(PocketSphinx DEFAULT_MSG
    POCKETSPHINX_LIBRARIES POCKETSPHINX_INCLUDE_DIRS)

list(APPEND POCKETSPHINX_INCLUDE_DIRS ${PC_POCKETSPHINX_INCLUDE_DIRS})

mark_as_advanced(POCKETSPHINX_INCLUDE_DIRS POCKETSPHINX_LIBRARIES)

execute_process(COMMAND ${PKGCONFIG_EXECUTABLE} pocketsphinx --variable=modeldir RESULT_VARIABLE POCKETSPHINX_MODELDIR)
